JBDS-4133 - Upgrade to Lucene 5.4.1
Due to org.jboss.tools.ws.jaxrs.core :: error occurred during JAX-RS Metamodel build:
java.lang.NoClassDefFoundError: org/apache/lucene/analysis/standard/StandardAnalyzer

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>